# -*- coding: utf-8 -*-
"""storing value using dict and tuple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F__-R8NusHe9FPNgGsey1VDQO4EHFxnR
"""

info = [('Mary','ABC School','SS000',('Y','Y','N','N')),('Alex','FGH School','SS999',('N','Y','Y','N'))]

user_student = input('your name? ')
user_school = input('your school? ')
user_SSID = input('your SSID? ')
attendance_list = []
for day in range(2):
  user_attendance = input('your attendance on the day %i AM? ' %(day+1))
  attendance_list.append(user_attendance)
  user_attendance = input('your attendance on the day %i PM? ' %(day+1))
  attendance_list.append(user_attendance)

user_attendance = tuple(attendance_list)
new = (user_student,user_school,user_SSID,user_attendance)
info.append(new)

student = []
school = []
SSID = []
attendance = []
attendpercent = []
for i in info:
  student.append(i[0])
  school.append(i[1])
  SSID.append(i[2])
  attendance.append(i[3])

for h in attendance:
  attendpercent.append(h.count('Y')/len(h)) 
  
print(attendpercent)
information = {'student': student, 'school': school, 'SSID': SSID, 'Attendance': attendance, 'Attendance percentage':attendpercent}

print ("{:<1} {:<10} {:<10} {:<10} {:<30} {:<10}".format(' ', 'NAME', 'SCHOOL', 'SSID', 'ATTENDANCE(1AM, 1PM, 2AM, 2PM)', 'ATTENDANCE PERCENTAGE')) 
  
for n in range(len(student)): 
    print ("{:<1} {:<10} {:<10} {:<10} {:<30} {:<10}".format(n+1, student[n], school[n], SSID[n], str(attendance[n]), attendpercent[n]))